### ISSUE TITLE
Update workflows to use shared ones from action-workflows

### ISSUE THREAD

**Issue by seansund** [cloud-native-toolkit/terraform-gitops-cp-watson-machine-learning#12]

**Comment by balasgit** [comment]
Code changes applied

**Comment by balasgit** [comment]
During the test, 
 - I noticed the 2 checks are pending for the testcase "ocp4_latest_gitops". 
 - I tried changing the test case server "ocp4_latest_gitops_cp4d" but it got stuck

**Comment by balasgit** [comment]
Blocked by #15 #14
