### ISSUE TITLE
Validate deploy on CP4D cluster is failing

### ISSUE THREAD

**Issue by balasgit** [cloud-native-toolkit/terraform-gitops-cp-watson-machine-learning#14]
Build error happens while trying to run the workflow - https://github.com/cloud-native-toolkit/terraform-gitops-cp-watson-machine-learning/runs/6334886628?check_suite_focus=true

Action Error 
Waiting for namespace: gitops-cp-watson-machine-learning
Waiting for namespace: gitops-cp-watson-machine-learning
Waiting for namespace: gitops-cp-watson-machine-learning
Waiting for namespace: gitops-cp-watson-machine-learning
Timed out waiting for namespace: gitops-cp-watson-machine-learning
Validation failed
Error: Process completed with exit code 1.

I tried to debug but not sure whether i need to have dependency running on that CP4D cluster

**Comment by triceam** [comment]
CP4D was not permanently deployed on the cluster.  it is now, and this should now work

**Comment by balasgit** [comment]
Verified the CP4D is installed fine as well as no modules in the test(https://github.com/cloud-native-toolkit-test/)).

Today I rerun the modules which is failing in the same step

Probably Snehal can investigate further since i don't have knowledge about this module. 
https://github.com/cloud-native-toolkit/terraform-gitops-cp-watson-machine-learning/runs/6598435248?check_suite_focus=true

**Comment by triceam** [comment]
The generated yaml is invalid.  You can see the error if you go into the Argo UI. 

<img width="1373" alt="image" src="https://user-images.githubusercontent.com/974294/170359190-a1663f03-ba68-4b7f-8eaa-be06e5cb31fb.png">

With the error message:



> rpc error: code = Unknown desc = `helm template . --name-template gitops-cp-watson-machine-learning-ocp4-cp4d-0-bootstrap --namespace openshift-gitops --kube-version 1.21 --set global.prefix=gitops-cp-watson-machine-learning-ocp4-cp4d --set global.groupLabel=gitops-cp-watson-machine-learning-ocp4-cp4d-gitops-bootstrap --api-versions acme.cert-manager.io/v1 --api-versions acme.cert-manager.io/v1/Challenge --api-versions acme.cert-manager.io/v1/Order --api-versions admissionregistration.k8s.io/v1 --api-versions admissionregistration.k8s.io/v1/MutatingWebhookConfiguration --api-versions admissionregistration.k8s.io/v1/ValidatingWebhookConfiguration --api-versions admissionregistration.k8s.io/v1beta1 --api-versions admissionregistration.k8s.io/v1beta1/MutatingWebhookConfiguration --api-versions admissionregistration.k8s.io/v1beta1/ValidatingWebhookConfiguration --api-versions apiextensions.k8s.io/v1 --api-versions apiextensions.k8s.io/v1/CustomResourceDefinition --api-versions apiextensions.k8s.io/v1beta1 --api-versions apiextensions.k8s.io/v1beta1/CustomResourceDefinition --api-versions apiregistration.k8s.io/v1 --api-versions apiregistration.k8s.io/v1/APIService --api-versions apiregistration.k8s.io/v1beta1 --api-versions apiregistration.k8s.io/v1beta1/APIService --api-versions apiserver.openshift.io/v1 --api-versions apiserver.openshift.io/v1/APIRequestCount --api-versions apps.openshift.io/v1 --api-versions apps.openshift.io/v1/DeploymentConfig --api-versions apps/v1 --api-versions apps/v1/ControllerRevision --api-versions apps/v1/DaemonSet --api-versions apps/v1/Deployment --api-versions apps/v1/ReplicaSet --api-versions apps/v1/StatefulSet --api-versions argoproj.io/v1alpha1 --api-versions argoproj.io/v1alpha1/AppProject --api-versions argoproj.io/v1alpha1/Application --api-versions argoproj.io/v1alpha1/ApplicationSet --api-versions argoproj.io/v1alpha1/ArgoCD --api-versions assistant.watson.ibm.com/v1 --api-versions assistant.watson.ibm.com/v1/TemporaryPatch --api-versions assistant.watson.ibm.com/v1/WatsonAssistant --api-versions assistant.watson.ibm.com/v1/WatsonAssistantAnalytics --api-versions assistant.watson.ibm.com/v1/WatsonAssistantAutolearn --api-versions assistant.watson.ibm.com/v1/WatsonAssistantClu --api-versions assistant.watson.ibm.com/v1/WatsonAssistantDialog --api-versions assistant.watson.ibm.com/v1/WatsonAssistantDvt --api-versions assistant.watson.ibm.com/v1/WatsonAssistantIntegrations --api-versions assistant.watson.ibm.com/v1/WatsonAssistantRecommends --api-versions assistant.watson.ibm.com/v1/WatsonAssistantStore --api-versions assistant.watson.ibm.com/v1/WatsonAssistantUi --api-versions audit.watson.ibm.com/v1beta1 --api-versions audit.watson.ibm.com/v1beta1/AuditWebhook --api-versions authorization.openshift.io/v1 --api-versions authorization.openshift.io/v1/RoleBindingRestriction --api-versions autoscaling/v1 --api-versions autoscaling/v1/HorizontalPodAutoscaler --api-versions autoscaling/v2beta1 --api-versions autoscaling/v2beta1/HorizontalPodAutoscaler --api-versions autoscaling/v2beta2 --api-versions autoscaling/v2beta2/HorizontalPodAutoscaler --api-versions batch/v1 --api-versions batch/v1/CronJob --api-versions batch/v1/Job --api-versions batch/v1beta1 --api-versions batch/v1beta1/CronJob --api-versions bitnami.com/v1alpha1 --api-versions bitnami.com/v1alpha1/SealedSecret --api-versions build.openshift.io/v1 --api-versions build.openshift.io/v1/Build --api-versions build.openshift.io/v1/BuildConfig --api-versions ccs.cpd.ibm.com/v1beta1 --api-versions ccs.cpd.ibm.com/v1beta1/CCS --api-versions cert-manager.io/v1 --api-versions cert-manager.io/v1/Certificate --api-versions cert-manager.io/v1/CertificateRequest --api-versions cert-manager.io/v1/ClusterIssuer --api-versions cert-manager.io/v1/Issuer --api-versions certificates.k8s.io/v1 --api-versions certificates.k8s.io/v1/CertificateSigningRequest --api-versions certificates.k8s.io/v1beta1 --api-versions certificates.k8s.io/v1beta1/CertificateSigningRequest --api-versions certmanager.k8s.io/v1alpha1 --api-versions certmanager.k8s.io/v1alpha1/Certificate --api-versions certmanager.k8s.io/v1alpha1/CertificateRequest --api-versions certmanager.k8s.io/v1alpha1/Challenge --api-versions certmanager.k8s.io/v1alpha1/ClusterIssuer --api-versions certmanager.k8s.io/v1alpha1/Issuer --api-versions certmanager.k8s.io/v1alpha1/Order --api-versions cloudcredential.openshift.io/v1 --api-versions cloudcredential.openshift.io/v1/CredentialsRequest --api-versions config.openshift.io/v1 --api-versions config.openshift.io/v1/APIServer --api-versions config.openshift.io/v1/Authentication --api-versions config.openshift.io/v1/Build --api-versions config.openshift.io/v1/ClusterOperator --api-versions config.openshift.io/v1/ClusterVersion --api-versions config.openshift.io/v1/Console --api-versions config.openshift.io/v1/DNS --api-versions config.openshift.io/v1/FeatureGate --api-versions config.openshift.io/v1/Image --api-versions config.openshift.io/v1/Infrastructure --api-versions config.openshift.io/v1/Ingress --api-versions config.openshift.io/v1/Network --api-versions config.openshift.io/v1/OAuth --api-versions config.openshift.io/v1/OperatorHub --api-versions config.openshift.io/v1/Project --api-versions config.openshift.io/v1/Proxy --api-versions config.openshift.io/v1/Scheduler --api-versions console.openshift.io/v1 --api-versions console.openshift.io/v1/ConsoleCLIDownload --api-versions console.openshift.io/v1/ConsoleExternalLogLink --api-versions console.openshift.io/v1/ConsoleLink --api-versions console.openshift.io/v1/ConsoleNotification --api-versions console.openshift.io/v1/ConsoleQuickStart --api-versions console.openshift.io/v1/ConsoleYAMLSample --api-versions console.openshift.io/v1alpha1 --api-versions console.openshift.io/v1alpha1/ConsolePlugin --api-versions coordination.k8s.io/v1 --api-versions coordination.k8s.io/v1/Lease --api-versions coordination.k8s.io/v1beta1 --api-versions coordination.k8s.io/v1beta1/Lease --api-versions core.strimzi.io/v1beta2 --api-versions core.strimzi.io/v1beta2/StrimziPodSet --api-versions cpd.ibm.com/v1 --api-versions cpd.ibm.com/v1/Ibmcpd --api-versions crd.projectcalico.org/v1 --api-versions crd.projectcalico.org/v1/BGPConfiguration --api-versions crd.projectcalico.org/v1/BGPPeer --api-versions crd.projectcalico.org/v1/BlockAffinity --api-versions crd.projectcalico.org/v1/ClusterInformation --api-versions crd.projectcalico.org/v1/FelixConfiguration --api-versions crd.projectcalico.org/v1/GlobalNetworkPolicy --api-versions crd.projectcalico.org/v1/GlobalNetworkSet --api-versions crd.projectcalico.org/v1/HostEndpoint --api-versions crd.projectcalico.org/v1/IPAMBlock --api-versions crd.projectcalico.org/v1/IPAMConfig --api-versions crd.projectcalico.org/v1/IPAMHandle --api-versions crd.projectcalico.org/v1/IPPool --api-versions crd.projectcalico.org/v1/KubeControllersConfiguration --api-versions crd.projectcalico.org/v1/NetworkPolicy --api-versions crd.projectcalico.org/v1/NetworkSet --api-versions databases.cpd.ibm.com/v1 --api-versions databases.cpd.ibm.com/v1/Db2oltpService --api-versions databases.cpd.ibm.com/v1/Db2whService --api-versions datarefinery.cpd.ibm.com/v1beta1 --api-versions datarefinery.cpd.ibm.com/v1beta1/DataRefinery --api-versions db2u.databases.ibm.com/v1 --api-versions db2u.databases.ibm.com/v1/Db2uCluster --api-versions db2u.databases.ibm.com/v1/DvService --api-versions db2u.databases.ibm.com/v1/Formation --api-versions db2u.databases.ibm.com/v1/FormationLock --api-versions db2u.databases.ibm.com/v1alpha1 --api-versions db2u.databases.ibm.com/v1alpha1/BigSQL --api-versions db2u.databases.ibm.com/v1alpha1/Db2uHadr --api-versions db2u.databases.ibm.com/v1alpha1/Db2uHelmMigration --api-versions default.cognitivedata/v1 --api-versions default.cognitivedata/v1/DataExhaust --api-versions default.cognitivedata/v1/DataExhaustArchive --api-versions default.cognitivedata/v1/DataExhaustConfigJob --api-versions default.cognitivedata/v1/DataExhaustDashboard --api-versions default.cognitivedata/v1/DataExhaustE2E --api-versions default.cognitivedata/v1/DataExhaustHealthcheck --api-versions default.cognitivedata/v1/DataExhaustKube --api-versions default.cognitivedata/v1/DataExhaustOverride --api-versions default.cognitivedata/v1/DataExhaustTenant --api-versions default.cognitivedata/v1/DataExhaustTenantOverride --api-versions default.cognitivedata/v1/ESTemplate --api-versions default.cognitivedata/v1/EtcdContent --api-versions default.cognitivedata/v1/EventStreamsTopics --api-versions default.cognitivedata/v1/IamService --api-versions discovery.k8s.io/v1 --api-versions discovery.k8s.io/v1/EndpointSlice --api-versions discovery.k8s.io/v1beta1 --api-versions discovery.k8s.io/v1beta1/EndpointSlice --api-versions dmc.databases.ibm.com/v1 --api-versions dmc.databases.ibm.com/v1/Db2console --api-versions dmc.databases.ibm.com/v1/Dmc --api-versions dmc.databases.ibm.com/v1/Dmcaddon --api-versions elasticsearch.opencontent.ibm.com/v1 --api-versions elasticsearch.opencontent.ibm.com/v1/ElasticsearchCluster --api-versions etcd.database.coreos.com/v1beta3 --api-versions etcd.database.coreos.com/v1beta3/EtcdBackup --api-versions etcd.database.coreos.com/v1beta3/EtcdCluster --api-versions etcd.database.coreos.com/v1beta3/EtcdRestore --api-versions events.k8s.io/v1 --api-versions events.k8s.io/v1/Event --api-versions events.k8s.io/v1beta1 --api-versions events.k8s.io/v1beta1/Event --api-versions extensions/v1beta1 --api-versions extensions/v1beta1/Ingress --api-versions flowcontrol.apiserver.k8s.io/v1beta1 --api-versions flowcontrol.apiserver.k8s.io/v1beta1/FlowSchema --api-versions flowcontrol.apiserver.k8s.io/v1beta1/PriorityLevelConfiguration --api-versions helm.openshift.io/v1beta1 --api-versions helm.openshift.io/v1beta1/HelmChartRepository --api-versions ibm.com/v1alpha1 --api-versions ibm.com/v1alpha1/RBACSync --api-versions ibmcpcs.ibm.com/v1 --api-versions ibmcpcs.ibm.com/v1/SecretShare --api-versions ibmevents.ibm.com/v1alpha1 --api-versions ibmevents.ibm.com/v1alpha1/KafkaBridge --api-versions ibmevents.ibm.com/v1alpha1/KafkaConnector --api-versions ibmevents.ibm.com/v1alpha1/KafkaMirrorMaker2 --api-versions ibmevents.ibm.com/v1alpha1/KafkaRebalance --api-versions ibmevents.ibm.com/v1beta1 --api-versions ibmevents.ibm.com/v1beta1/Kafka --api-versions ibmevents.ibm.com/v1beta1/KafkaConnect --api-versions ibmevents.ibm.com/v1beta1/KafkaConnectS2I --api-versions ibmevents.ibm.com/v1beta1/KafkaMirrorMaker --api-versions ibmevents.ibm.com/v1beta1/KafkaTopic --api-versions ibmevents.ibm.com/v1beta1/KafkaUser --api-versions ibmevents.ibm.com/v1beta2 --api-versions ibmevents.ibm.com/v1beta2/Kafka --api-versions ibmevents.ibm.com/v1beta2/KafkaBridge --api-versions ibmevents.ibm.com/v1beta2/KafkaConnect --api-versions ibmevents.ibm.com/v1beta2/KafkaConnectS2I --api-versions ibmevents.ibm.com/v1beta2/KafkaConnector --api-versions ibmevents.ibm.com/v1beta2/KafkaMirrorMaker --api-versions ibmevents.ibm.com/v1beta2/KafkaMirrorMaker2 --api-versions ibmevents.ibm.com/v1beta2/KafkaRebalance --api-versions ibmevents.ibm.com/v1beta2/KafkaTopic --api-versions ibmevents.ibm.com/v1beta2/KafkaUser --api-versions image.openshift.io/v1 --api-versions image.openshift.io/v1/Image --api-versions image.openshift.io/v1/ImageStream --api-versions imageregistry.operator.openshift.io/v1 --api-versions imageregistry.operator.openshift.io/v1/Config --api-versions imageregistry.operator.openshift.io/v1/ImagePruner --api-versions ingress.operator.openshift.io/v1 --api-versions ingress.operator.openshift.io/v1/DNSRecord --api-versions k8s.cni.cncf.io/v1 --api-versions k8s.cni.cncf.io/v1/NetworkAttachmentDefinition --api-versions kdmp.portworx.com/v1alpha1 --api-versions kdmp.portworx.com/v1alpha1/DataExport --api-versions kdmp.portworx.com/v1alpha1/VolumeBackup --api-versions machineconfiguration.openshift.io/v1 --api-versions machineconfiguration.openshift.io/v1/ContainerRuntimeConfig --api-versions machineconfiguration.openshift.io/v1/KubeletConfig --api-versions machineconfiguration.openshift.io/v1/MachineConfig --api-versions machineconfiguration.openshift.io/v1/MachineConfigPool --api-versions metal3.io/v1alpha1 --api-versions metal3.io/v1alpha1/BareMetalHost --api-versions metal3.io/v1alpha1/Provisioning --api-versions migration.k8s.io/v1alpha1 --api-versions migration.k8s.io/v1alpha1/StorageState --api-versions migration.k8s.io/v1alpha1/StorageVersionMigration --api-versions minio.opencontent.ibm.com/v1alpha1 --api-versions minio.opencontent.ibm.com/v1alpha1/MinioCluster --api-versions modeltrain.ibm.com/v1 --api-versions modeltrain.ibm.com/v1/ModelTrainDynamicWorkflow --api-versions monitoring.coreos.com/v1 --api-versions monitoring.coreos.com/v1/Alertmanager --api-versions monitoring.coreos.com/v1/PodMonitor --api-versions monitoring.coreos.com/v1/Probe --api-versions monitoring.coreos.com/v1/Prometheus --api-versions monitoring.coreos.com/v1/PrometheusRule --api-versions monitoring.coreos.com/v1/ServiceMonitor --api-versions monitoring.coreos.com/v1/ThanosRuler --api-versions monitoring.coreos.com/v1alpha1 --api-versions monitoring.coreos.com/v1alpha1/AlertmanagerConfig --api-versions network.operator.openshift.io/v1 --api-versions network.operator.openshift.io/v1/EgressRouter --api-versions network.operator.openshift.io/v1/OperatorPKI --api-versions networking.k8s.io/v1 --api-versions networking.k8s.io/v1/Ingress --api-versions networking.k8s.io/v1/IngressClass --api-versions networking.k8s.io/v1/NetworkPolicy --api-versions networking.k8s.io/v1beta1 --api-versions networking.k8s.io/v1beta1/Ingress --api-versions networking.k8s.io/v1beta1/IngressClass --api-versions node.k8s.io/v1 --api-versions node.k8s.io/v1/RuntimeClass --api-versions node.k8s.io/v1beta1 --api-versions node.k8s.io/v1beta1/RuntimeClass --api-versions oauth.openshift.io/v1 --api-versions oauth.openshift.io/v1/OAuthAccessToken --api-versions oauth.openshift.io/v1/OAuthAuthorizeToken --api-versions oauth.openshift.io/v1/OAuthClient --api-versions oauth.openshift.io/v1/OAuthClientAuthorization --api-versions oauth.openshift.io/v1/UserOAuthAccessToken --api-versions operator.ibm.com/v1 --api-versions operator.ibm.com/v1/IBMLicensingDefinition --api-versions operator.ibm.com/v1/IBMLicensingQuerySource --api-versions operator.ibm.com/v1/NamespaceScope --api-versions operator.ibm.com/v1alpha1 --api-versions operator.ibm.com/v1alpha1/CertManager --api-versions operator.ibm.com/v1alpha1/IBMLicenseServiceReporter --api-versions operator.ibm.com/v1alpha1/IBMLicensing --api-versions operator.ibm.com/v1alpha1/IBMLicensingMetadata --api-versions operator.ibm.com/v1alpha1/OperandBindInfo --api-versions operator.ibm.com/v1alpha1/OperandConfig --api-versions operator.ibm.com/v1alpha1/OperandRegistry --api-versions operator.ibm.com/v1alpha1/OperandRequest --api-versions operator.ibm.com/v1alpha1/PodPreset --api-versions operator.ibm.com/v3 --api-versions operator.ibm.com/v3/CommonService --api-versions operator.openshift.io/v1 --api-versions operator.openshift.io/v1/Authentication --api-versions operator.openshift.io/v1/CSISnapshotController --api-versions operator.openshift.io/v1/CloudCredential --api-versions operator.openshift.io/v1/ClusterCSIDriver --api-versions operator.openshift.io/v1/Config --api-versions operator.openshift.io/v1/Console --api-versions operator.openshift.io/v1/DNS --api-versions operator.openshift.io/v1/Etcd --api-versions operator.openshift.io/v1/IngressController --api-versions operator.openshift.io/v1/KubeAPIServer --api-versions operator.openshift.io/v1/KubeControllerManager --api-versions operator.openshift.io/v1/KubeScheduler --api-versions operator.openshift.io/v1/KubeStorageVersionMigrator --api-versions operator.openshift.io/v1/Network --api-versions operator.openshift.io/v1/OpenShiftAPIServer --api-versions operator.openshift.io/v1/OpenShiftControllerManager --api-versions operator.openshift.io/v1/ServiceCA --api-versions operator.openshift.io/v1/Storage --api-versions operator.openshift.io/v1alpha1 --api-versions operator.openshift.io/v1alpha1/ImageContentSourcePolicy --api-versions operator.tekton.dev/v1alpha1 --api-versions operator.tekton.dev/v1alpha1/TektonAddon --api-versions operator.tekton.dev/v1alpha1/TektonConfig --api-versions operator.tekton.dev/v1alpha1/TektonPipeline --api-versions operator.tekton.dev/v1alpha1/TektonTrigger --api-versions operator.tigera.io/v1 --api-versions operator.tigera.io/v1/APIServer --api-versions operator.tigera.io/v1/ImageSet --api-versions operator.tigera.io/v1/Installation --api-versions operator.tigera.io/v1/TigeraStatus --api-versions operators.coreos.com/v1 --api-versions operators.coreos.com/v1/Operator --api-versions operators.coreos.com/v1/OperatorCondition --api-versions operators.coreos.com/v1/OperatorGroup --api-versions operators.coreos.com/v1alpha1 --api-versions operators.coreos.com/v1alpha1/CatalogSource --api-versions operators.coreos.com/v1alpha1/ClusterServiceVersion --api-versions operators.coreos.com/v1alpha1/InstallPlan --api-versions operators.coreos.com/v1alpha1/Subscription --api-versions operators.coreos.com/v1alpha2 --api-versions operators.coreos.com/v1alpha2/OperatorGroup --api-versions operators.coreos.com/v2 --api-versions operators.coreos.com/v2/OperatorCondition --api-versions pipelines.openshift.io/v1alpha1 --api-versions pipelines.openshift.io/v1alpha1/GitopsService --api-versions policy/v1 --api-versions policy/v1/PodDisruptionBudget --api-versions policy/v1beta1 --api-versions policy/v1beta1/PodDisruptionBudget --api-versions policy/v1beta1/PodSecurityPolicy --api-versions postgresql.k8s.enterprisedb.io/v1 --api-versions postgresql.k8s.enterprisedb.io/v1/Backup --api-versions postgresql.k8s.enterprisedb.io/v1/Cluster --api-versions postgresql.k8s.enterprisedb.io/v1/Pooler --api-versions postgresql.k8s.enterprisedb.io/v1/ScheduledBackup --api-versions project.openshift.io/v1 --api-versions project.openshift.io/v1/Project --api-versions quota.openshift.io/v1 --api-versions quota.openshift.io/v1/ClusterResourceQuota --api-versions rabbitmq.opencontent.ibm.com/v1alpha1 --api-versions rabbitmq.opencontent.ibm.com/v1alpha1/RabbitMQCluster --api-versions rbac.authorization.k8s.io/v1 --api-versions rbac.authorization.k8s.io/v1/ClusterRole --api-versions rbac.authorization.k8s.io/v1/ClusterRoleBinding --api-versions rbac.authorization.k8s.io/v1/Role --api-versions rbac.authorization.k8s.io/v1/RoleBinding --api-versions rbac.authorization.k8s.io/v1beta1 --api-versions rbac.authorization.k8s.io/v1beta1/ClusterRole --api-versions rbac.authorization.k8s.io/v1beta1/ClusterRoleBinding --api-versions rbac.authorization.k8s.io/v1beta1/Role --api-versions rbac.authorization.k8s.io/v1beta1/RoleBinding --api-versions redis.databases.cloud.ibm.com/v1 --api-versions redis.databases.cloud.ibm.com/v1/Backup --api-versions redis.databases.cloud.ibm.com/v1/Bucket --api-versions redis.databases.cloud.ibm.com/v1/Formation --api-versions redis.databases.cloud.ibm.com/v1/FormationLock --api-versions redis.databases.cloud.ibm.com/v1/Recipe --api-versions redis.databases.cloud.ibm.com/v1/RecipeTemplate --api-versions redis.databases.cloud.ibm.com/v1/RedisSentinel --api-versions redis.databases.cloud.ibm.com/v1/Release --api-versions route.openshift.io/v1 --api-versions route.openshift.io/v1/Route --api-versions runtimes.ibm.com/v1alpha1 --api-versions runtimes.ibm.com/v1alpha1/RuntimeAssembly --api-versions samples.operator.openshift.io/v1 --api-versions samples.operator.openshift.io/v1/Config --api-versions scheduling.k8s.io/v1 --api-versions scheduling.k8s.io/v1/PriorityClass --api-versions scheduling.k8s.io/v1beta1 --api-versions scheduling.k8s.io/v1beta1/PriorityClass --api-versions security.internal.openshift.io/v1 --api-versions security.internal.openshift.io/v1/RangeAllocation --api-versions security.openshift.io/v1 --api-versions security.openshift.io/v1/RangeAllocation --api-versions security.openshift.io/v1/SecurityContextConstraints --api-versions snapshot.storage.k8s.io/v1 --api-versions snapshot.storage.k8s.io/v1/VolumeSnapshot --api-versions snapshot.storage.k8s.io/v1/VolumeSnapshotClass --api-versions snapshot.storage.k8s.io/v1/VolumeSnapshotContent --api-versions snapshot.storage.k8s.io/v1beta1 --api-versions snapshot.storage.k8s.io/v1beta1/VolumeSnapshot --api-versions snapshot.storage.k8s.io/v1beta1/VolumeSnapshotClass --api-versions snapshot.storage.k8s.io/v1beta1/VolumeSnapshotContent --api-versions storage.k8s.io/v1 --api-versions storage.k8s.io/v1/CSIDriver --api-versions storage.k8s.io/v1/CSINode --api-versions storage.k8s.io/v1/StorageClass --api-versions storage.k8s.io/v1/VolumeAttachment --api-versions storage.k8s.io/v1beta1 --api-versions storage.k8s.io/v1beta1/CSIDriver --api-versions storage.k8s.io/v1beta1/CSINode --api-versions storage.k8s.io/v1beta1/CSIStorageCapacity --api-versions storage.k8s.io/v1beta1/StorageClass --api-versions storage.k8s.io/v1beta1/VolumeAttachment --api-versions stork.libopenstorage.org/v1alpha1 --api-versions stork.libopenstorage.org/v1alpha1/ApplicationBackup --api-versions stork.libopenstorage.org/v1alpha1/ApplicationBackupSchedule --api-versions stork.libopenstorage.org/v1alpha1/ApplicationClone --api-versions stork.libopenstorage.org/v1alpha1/ApplicationRegistration --api-versions stork.libopenstorage.org/v1alpha1/ApplicationRestore --api-versions stork.libopenstorage.org/v1alpha1/BackupLocation --api-versions stork.libopenstorage.org/v1alpha1/ClusterDomainUpdate --api-versions stork.libopenstorage.org/v1alpha1/ClusterDomainsStatus --api-versions stork.libopenstorage.org/v1alpha1/ClusterPair --api-versions stork.libopenstorage.org/v1alpha1/GroupVolumeSnapshot --api-versions stork.libopenstorage.org/v1alpha1/Migration --api-versions stork.libopenstorage.org/v1alpha1/MigrationSchedule --api-versions stork.libopenstorage.org/v1alpha1/NamespacedSchedulePolicy --api-versions stork.libopenstorage.org/v1alpha1/Rule --api-versions stork.libopenstorage.org/v1alpha1/SchedulePolicy --api-versions stork.libopenstorage.org/v1alpha1/VolumeSnapshotRestore --api-versions stork.libopenstorage.org/v1alpha1/VolumeSnapshotSchedule --api-versions tekton.dev/v1alpha1 --api-versions tekton.dev/v1alpha1/ClusterTask --api-versions tekton.dev/v1alpha1/Condition --api-versions tekton.dev/v1alpha1/Pipeline --api-versions tekton.dev/v1alpha1/PipelineResource --api-versions tekton.dev/v1alpha1/PipelineRun --api-versions tekton.dev/v1alpha1/Run --api-versions tekton.dev/v1alpha1/Task --api-versions tekton.dev/v1alpha1/TaskRun --api-versions tekton.dev/v1beta1 --api-versions tekton.dev/v1beta1/ClusterTask --api-versions tekton.dev/v1beta1/Pipeline --api-versions tekton.dev/v1beta1/PipelineRun --api-versions tekton.dev/v1beta1/Task --api-versions tekton.dev/v1beta1/TaskRun --api-versions template.openshift.io/v1 --api-versions template.openshift.io/v1/BrokerTemplateInstance --api-versions template.openshift.io/v1/Template --api-versions template.openshift.io/v1/TemplateInstance --api-versions triggers.tekton.dev/v1alpha1 --api-versions triggers.tekton.dev/v1alpha1/ClusterInterceptor --api-versions triggers.tekton.dev/v1alpha1/ClusterTriggerBinding --api-versions triggers.tekton.dev/v1alpha1/EventListener --api-versions triggers.tekton.dev/v1alpha1/Trigger --api-versions triggers.tekton.dev/v1alpha1/TriggerBinding --api-versions triggers.tekton.dev/v1alpha1/TriggerTemplate --api-versions tuned.openshift.io/v1 --api-versions tuned.openshift.io/v1/Profile --api-versions tuned.openshift.io/v1/Tuned --api-versions user.openshift.io/v1 --api-versions user.openshift.io/v1/Group --api-versions user.openshift.io/v1/Identity --api-versions user.openshift.io/v1/User --api-versions v1 --api-versions v1/ConfigMap --api-versions v1/Endpoints --api-versions v1/Event --api-versions v1/LimitRange --api-versions v1/Namespace --api-versions v1/Node --api-versions v1/PersistentVolume --api-versions v1/PersistentVolumeClaim --api-versions v1/Pod --api-versions v1/PodTemplate --api-versions v1/ReplicationController --api-versions v1/ResourceQuota --api-versions v1/Secret --api-versions v1/Service --api-versions v1/ServiceAccount --api-versions volumesnapshot.external-storage.k8s.io/v1 --api-versions volumesnapshot.external-storage.k8s.io/v1/VolumeSnapshot --api-versions volumesnapshot.external-storage.k8s.io/v1/VolumeSnapshotData --api-versions watson-gateway.watson.ibm.com/v1 --api-versions watson-gateway.watson.ibm.com/v1/WatsonGateway --api-versions whereabouts.cni.cncf.io/v1alpha1 --api-versions whereabouts.cni.cncf.io/v1alpha1/IPPool --api-versions whereabouts.cni.cncf.io/v1alpha1/OverlappingRangeIPReservation --api-versions ws.cpd.ibm.com/v1beta1 --api-versions ws.cpd.ibm.com/v1beta1/NotebookRuntime --api-versions ws.cpd.ibm.com/v1beta1/WS --api-versions zen.cpd.ibm.com/v1 --api-versions zen.cpd.ibm.com/v1/ZenService --include-crds` failed exit status 1: Error: release name "gitops-cp-watson-machine-learning-ocp4-cp4d-0-bootstrap": invalid release name, must match regex ^[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*$ and the length must not be longer than 53

**Comment by balasgit** [comment]
Thanks Andy.. 

Why suddenly all modules are hitting length issues which was working fine earlier. I noticed Sasikanth mentioned the same issues for another CP4D module (https://ibm-cloudplatform.slack.com/archives/C02KB99P2JC/p1653468683067919)

**Comment by balasgit** [comment]
This steps needs to happen which may fix the issues

* Update the module name in the module.yaml
* Rename the Repository name in Github module settings


Validating with  Sasikanth above steps since he fixed issues recently.

**Comment by balasgit** [comment]
Based on the github action tab, the developers fixed the issues. Hence closing the issues since this issue was not associated with PR merge
